cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('',
         include(('store.urls', 'store'), namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    # path('create', views.order_create,name='order_create'),
    path('create', views.OrderView.as_view(), name='order_create')
]

store/urls.py
from django.urls import path
from .views import ProductListView, ProductDetail, product_detail

app_name = 'store'
urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<int:id>/<slug:slug>/', product_detail,
         name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from store.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    city = models.CharField(max_length=50)
    adress = models.CharField(max_length=300)
    postal_code = models.CharField(max_length=6)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order{self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    # def get_absolute_url(self):
    #     return f'succes/{self.id}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

store/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_list',
                       )


class Producer(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True)

    class Meta:
        verbose_name_plural = 'producers'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    producer = models.ForeignKey(Producer, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)

    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name','email', 'adress',
                  'postal_code', 'city']

cart/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from cart.cart import Cart
from cart.forms import CartAddProductForm
from store.models import Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['override'])
        print(cd)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity':item['quantity'],
                     'override':True})
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.views import View
from django.shortcuts import render
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created


class OrderView(View):
    model = Order
    form_class = OrderCreateForm
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, 'orders/order/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        cart = Cart(request)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            order_created.delay(order.id)
            return render(request,
                          'orders/order/created.html',
                          {'order': order})

store/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Category, Producer, Product
from .filters import ProductFilter
from cart.forms import CartAddProductForm


class ProductListView(ListView):
    model = Product
    template_name = 'store/products/product_list.html'
    paginate_by = 8

    def get_queryset(self):
        queryset = super().get_queryset().filter(is_active=True)
        return ProductFilter(self.request.GET, queryset=queryset).qs

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list
        queryset.filter(is_active=False)
        my_filter= ProductFilter(self.request.GET, queryset=queryset)
        return super().get_context_data(
            object_list=queryset,
            filter=my_filter,
            **kwargs)


class ProductDetail(DetailView):
    model = Product
    template_name = 'store/products/product_detail.html'


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                in_stock=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'store/products/product_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
Shopping cart
{% endblock %}
{% block content %}
<h1>Shopping cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th></th>
        <th>Product</th>
        <th>Amount</th>
        <th>Delete</th>
        <th>Price per item</th>
        <th>Total for item</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_image.png' %}{% endif %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
            <input type="submit" value="Change by">
            {% csrf_token %}
            </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}">Delete</a></td>
        <td class="num">{{ item.price }} zł</td>
        <td class="num">{{ item.total_price }} zł</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} zł</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'store:product_list' %}" class="button
    light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">To register</a>
</p>
{% endblock %}

store/templates/store/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My store{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">

</head>
<body>

<div id="header">
    <a href="/" class="logo">My store</a>
    <div class="cart">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        Cart:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} product{{ total_items|pluralize:"y" }},
            {{ cart.get_total_price }} zł
        </a>
        {% else %}
        Your cart is empty..
        {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

store/templates/store/pagination.html
{% load my_tags %}
{% load static %}
<div class="center">
    <div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            {% else %}
      <a class="disabled"><span>&laquo;</span></a>
        {% endif %}

        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <a class="active"><span>{{ i }} </span></a>
        {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
        {% endif %}
        {% endfor %}
            {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    {% else %}
      <a class="disabled"><span>&raquo;</span></a>
            {% endif %}
    </div>
</div>

store/templates/store/product_list.html
{% extends "store/base.html" %}
{% load static %}
{% block content %}

<div id="sidebar">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <form method="get">
        {{ filter.form.as_div}}
        <button type="submit">search</button>
    </form>
</div>
<div id="main">

    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in object_list %}
    <div class="responsive">
        <a href="{{ product.get_absolute_url }}"></a>
        <div class="gallery">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static
    ' img/no_image.png' %}{% endif %}">
            </a>
            <div class="desc">
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                        {{ product.price }} $
            </div>

        </div>
    </div>

    {% endfor %}

    <table id="myTable" border="1">
        <caption>Products</caption>
        <thead>
        <tr>
            <th>category</th>
            <th>name</th>
            <th>amount</th>
        </tr>
        </thead>
        <tbody>

        {% for obj in object_list %}
        <tr class="table">
            <td>{{ obj.category|default:"-" }}</td>
            <td>{{ obj.name|default:"-" }}</td>
            <td>{{ obj.price|floatformat:2 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
<div style="margin-left:23%">{% include "store/pagination.html" %}</div>
{% endblock %}

store/templates/store/products/product_detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Produkty{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">{{ product.price }} zł</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Dodaj do koszyka">
    </form>
    {{ product.description|linebreaks }}
</div>
{% endblock %}

store/templates/store/test.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {margin:0;}

.navbar {
  overflow: hidden;
  background-color: #333;
  position: fixed;
  top: 0;
  width: 100%;
}

.navbar a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.navbar a:hover {
  background: #ddd;
  color: black;
}

.main {
  padding: 16px;
  margin-top: 30px;
  height: 1500px; /* Used in this example to enable scrolling */
}
</style>
</head>
<body>

<div class="navbar">
  <a href="#home">Home</a>
  <a href="#news">News</a>
  <a href="#contact">Contact</a>
</div>

<div class="main">
  <h1>Fixed Top Menu</h1>
  <h2>Scroll this page to see the effect</h2>
  <h2>The navigation bar will stay at the top of the page while scrolling</h2>

  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
  <p>Some text some text some text some text..</p>
</div>

</body>
</html>